stages:
  - run_always
  - test
  - deploy

pipeline_complete_if_no_action:
  stage: run_always
  script:
    - echo "Child pipeline is considered successful if no manual action is taken."

include:
  - component: $CI_SERVER_FQDN/components/docker/config-docker@~latest
    inputs:
      as: "docker-lint"
      local_path: "deployments/node-exporter-cloudy-vm-1"

  - component: $CI_SERVER_FQDN/components/docker/deploy@~latest
    inputs:
      as: "cloudy-vm-1-deploy"
      local_path: "deployments/node-exporter-cloudy-vm-1"
      remote_host: "cloudy-vm.margusm.dev"
      remote_user: "margus"
      remote_path: "deployments/node-exporter-cloudy-vm-1"