---
services:
  prometheus:
    image: docker.io/prom/prometheus:v3.6.0
    container_name: prometheus-cloudy-vm-1
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring
volumes:
  prometheus-data:
    driver: local
networks:
  monitoring:
    name: monitoring
    driver: bridge
    attachable: true